### PR TITLE
Do not use fstab.sys

### PR DESCRIPTION
**Pull request by Vogtinator**
fstab.sys is a hack, it works around systemd and the boot process without caring about dependencies and general state of the system.

By marking the /etc entry with `x-initrd.mount,x-systemd.requires-mounts-for=/var`, systemd creates mount units with the right dependencies:

```
> systemctl list-dependencies etc.mount
etc.mount
● ├─-.mount
● ├─system.slice
● └─var.mount
```

(previously var.mount was not listed)

```
> systemctl list-dependencies --reverse etc.mount | wc -l
60
```

(was previously empty)

This ensures right ordering on boot and shutdown. I did not see any error or warning messages anymore, while there were a couple before.

Unfortunately, systemd-fstab-generator is severely broken (boo#1121276, boo#1121279), so ugly workarounds are added. This makes this PR unmergable before at least boo#1121276 is fixed :-(

Also, this needs code in transactional-update to read/write /etc/fstab instead of fstab.sys, but that also depends on boo#1121276.

### CODE REVIEW

**Comment by Vogtinator** [comment]
I did some more testing:
* Adding mountpoints to the /etc/fstab in the overlay works as expected
* The "dracut-pre-pivot: device node not found" errors on boot are gone
* The system boots faster as the mounting is done in parallel with startup

**Comment by Vogtinator** [comment]
Not RFC anymore, transactional-update change is ready.

Needs some changes in `read-only-root-fs.spec`:

- Create `/var/lib/overlay/1/etc` instead of /var/lib/overlay/etc`
- Remove conditions in `%post`, e.g. `%post -p %{_sbindir}/setup-fstab-for-overlayfs`
- `Requires(post): gawk bash coreutils` (the others can be removed)

**Comment by laenion** [comment]
It would be good to have this merged (and thus packaged) before the release of *SUSE*-15-SP1. transactional-update will migrate /etc/fstab.sys to /etc/fstab independent of this change, but it would be nice if the file would already be created correctly during installation.

**Comment by Vogtinator** [comment]
@thkukuk ^

**Pull request merged**
